const ZONING=DATA.zoning,workshopById=Object.fromEntries(ZONING.workshops.map(w=>[w.id,w]));
const zoneDefaults={zoneLayout:'rail',zoneStage:'0',zoneMaterialType:'all',zoneRecipeSearch:'',zoneRecipeFilter:'active',zoneWorkshop:'all'};
let chosenZone='utilities';
function resetZones(){for(const[id,v]of Object.entries(zoneDefaults))$(id).value=v;chosenZone='utilities';}
function materialName(material){const i=material.indexOf(':'),type=material.slice(0,i),id=material.slice(i+1);let label=name(id,type==='fluid'?'fluid-name':'item-name');if(label===id&&type==='item')label=name(id,'entity-name');if(label===id&&id.startsWith('nullius-box-'))label='箱装 '+name(id.replace('nullius-box-','nullius-'),'item-name');return label;}
function materialHTML(material){return `${esc(materialName(material))}<small class="id">${esc(material)}</small>`;}
function zonesModel(s){const plan=s.plans[+$('zoneStage').value],layout=$('zoneLayout').value,data=ZONING.scenarios[plan.name][layout];if(!data.zones.some(z=>z.id===chosenZone))chosenZone=data.zones[0].id;return{plan,layout,data,zone:data.zones.find(z=>z.id===chosenZone),base:ZONING.scenarios[s.plans[0].name][layout].zones.find(z=>z.id===chosenZone)};}
function materialVisible(m){return $('zoneMaterialType').value==='all'||m.startsWith($('zoneMaterialType').value+':');}
function netList(net,sign){return Object.entries(net).filter(([m,v])=>materialVisible(m)&&v*sign>1e-6).sort((a,b)=>Math.abs(b[1])-Math.abs(a[1]));}
function renderZones(s){const m=zonesModel(s),z=m.zone;let count=m.data.zones.length;
 $('zoneStatus').textContent=`${labels[m.plan.name]} · ${m.plan.future_projection?'未来规划':'当前可用'} · ${count} 个区 / 工段 · 各瓶 ${fmt(s.rate)}/s · 基准物料残差 < 0.0001/s`;
 $('zoneMap').innerHTML=m.data.zones.map(zone=>`<button class="zone-card" data-zone="${zone.id}" aria-pressed="${zone.id===chosenZone}"><strong>${esc(zone.name)}</strong><small>${zone.members.map(w=>esc(workshopById[w].name)).join(' + ')}</small><small>${fmt(zone.recipes.reduce((n,r)=>n+r.machines,0)*s.scale,0)} 台等效 · ${zone.recipes.length} 条工段配方</small></button>`).join('');
 $('zoneHeading').innerHTML=`<h2>${esc(z.name)}</h2>${z.members.map(id=>`<p><strong>${esc(workshopById[id].name)}：</strong>${esc(workshopById[id].factories)}。<span class="muted">${esc(workshopById[id].placement)}</span></p>`).join('')}`;
 const input=netList(z.net,-1),output=netList(z.net,1),zones=Object.fromEntries(m.data.zones.map(zone=>[zone.id,zone.name])),pool=Object.fromEntries(m.data.materials.map(mat=>[mat.material,mat]));
 function ports(entries,dir){return entries.length?entries.map(([mat,v])=>{const p=pool[mat],others=(dir==='in'?p.exporters:p.importers).filter(e=>e.zone!==z.id).map(e=>`${zones[e.zone]} ${fmt(e.rate*s.scale,1)}/s`);if(dir==='in'&&p.external_supply>1e-6)others.unshift(`外部矿区 ${fmt(p.external_supply*s.scale,1)}/s`);if(dir==='out'&&!others.length)others.push(mat.includes('-pack')?'实验室 / 科研库存':'边界输出');return `<tr><td class="zone-material">${materialHTML(mat)}<small>${esc(others.join('；'))}</small></td><td class="number">${fmt(Math.abs(v)*s.scale,2)}</td></tr>`;}).join(''):'<tr><td colspan="2" class="empty">当前物料筛选下没有净接口。</td></tr>';}
 $('zoneInputs').innerHTML=ports(input,'in');$('zoneOutputs').innerHTML=ports(output,'out');
 function localRows(values){let list=Object.entries(values).filter(([mat,v])=>materialVisible(mat)&&v>1e-6).sort((a,b)=>b[1]-a[1]);return list.length?list.map(([mat,v])=>`<tr><td class="zone-material">${materialHTML(mat)}</td><td class="number">${fmt(v*s.scale,2)}</td></tr>`).join(''):'<tr><td colspan="2" class="empty">无记录。</td></tr>';}
 $('zoneReuse').innerHTML=localRows(z.internal_reuse);$('zoneDisposal').innerHTML=localRows(z.disposal);
 const fullIn=Object.entries(z.net).filter(([,v])=>v< -1e-6),fullOut=Object.entries(z.net).filter(([,v])=>v>1e-6),fluids=a=>a.filter(([k])=>k.startsWith('fluid:')).length;
 $('zoneConnections').innerHTML=`<strong>${m.layout==='rail'?'站场接口':'总线接口'}：</strong>输入 ${fluids(fullIn)} 种流体 / ${fullIn.length-fluids(fullIn)} 种固体，输出 ${fluids(fullOut)} 种流体 / ${fullOut.length-fluids(fullOut)} 种固体。${m.layout==='rail'?'这是接口清单，不代表每种物料都必须独立建站；相邻区的大流量液体优先直连管网。':'流体分网、固体分带；优先短支线与副产回流支线。'}<br>设备电功率 ${fmt(z.recipes.filter(r=>r.energy_type==='electric').reduce((n,r)=>n+r.MW,0)*s.scale,1)} MW；外供热功率 ${fmt(z.recipes.filter(r=>r.energy_type==='heat').reduce((n,r)=>n+r.MW,0)*s.scale,1)} MW。`;
 let machines={};for(const r of z.recipes){machines[r.machine]??={equivalent:0,build:0};machines[r.machine].equivalent+=r.machines*s.scale;machines[r.machine].build+=ceil(r.machines*s.scale);}
 $('zoneEquipmentSummary').textContent=`${Object.keys(machines).length} 种设备 · ${fmt(Object.values(machines).reduce((n,r)=>n+r.equivalent,0),1)} 台连续等效 · ${fmt(Object.values(machines).reduce((n,r)=>n+r.build,0),0)} 台按工段配方取整`;
 $('zoneEquipment').innerHTML=Object.entries(machines).sort((a,b)=>b[1].equivalent-a[1].equivalent).map(([id,v])=>`<div>${esc(name(id,'entity-name'))}<strong>${fmt(v.build,0)} 台</strong><small>等效 ${fmt(v.equivalent,2)} 台</small><div class="id">${esc(id)}</div></div>`).join('');
 const previous=$('zoneWorkshop').value;$('zoneWorkshop').innerHTML='<option value="all">本区全部工段</option>'+z.members.map(id=>`<option value="${id}">${esc(workshopById[id].name)}</option>`).join('');$('zoneWorkshop').value=z.members.includes(previous)?previous:'all';renderZoneRecipes(s,m);
}
function renderZoneRecipes(s,m){const z=m.zone,base=m.base,q=$('zoneRecipeSearch').value.trim().toLowerCase(),filter=$('zoneRecipeFilter').value,workshop=$('zoneWorkshop').value,key=r=>r.workshop+':'+r.recipe,old=Object.fromEntries(base.recipes.map(r=>[key(r),r])),now=Object.fromEntries(z.recipes.map(r=>[key(r),r]));
 let list=(filter==='removed'?base.recipes:z.recipes).filter(r=>(workshop==='all'||r.workshop===workshop)&&(filter==='active'||filter==='new'&&!old[key(r)]||filter==='removed'&&!now[key(r)])).filter(r=>{const def=ZONING.definitions[r.recipe];return !q||[r.recipe,recipeName(r.recipe),r.machine,name(r.machine,'entity-name'),...[...def.ingredients,...def.results].map(e=>materialName(e.material))].join(' ').toLowerCase().includes(q);}).sort((a,b)=>b.machines-a.machines);
 $('zoneRecipeCount').textContent=`${list.length} 条 · 点击展开投入 / 产出配方`;
 $('zoneRecipes').innerHTML=list.length?list.map(r=>{const def=ZONING.definitions[r.recipe],removed=filter==='removed',rate=removed?0:r.crafts_per_second*s.scale,previous=old[key(r)],diff=((removed?0:r.machines)-(previous?.machines||0))*s.scale;function formula(entries){return entries.map(e=>`<p>${esc(materialName(e.material))} × ${fmt(e.amount,4)}<br><small>${fmt(e.amount*rate,2)} /s</small></p>`).join('')||'<p>无</p>';}
 return `<details class="zone-recipe"><summary><strong>${esc(recipeName(r.recipe))}</strong> <span class="tag">${esc(workshopById[r.workshop].name)}</span> ${removed?'<span class="tag future">本方案停用</span>':!previous?'<span class="tag">新增启用</span>':''}<div class="id">${esc(r.recipe)}</div><div>${esc(name(r.machine,'entity-name'))} · ${fmt(rate,3)} 次/s · ${removed?'0':fmt(r.machines*s.scale,2)} 台等效 / ${removed?'0':ceil(r.machines*s.scale)} 台建造参考 · 相对 A ${diff>=0?'+':''}${fmt(diff,2)} 台</div></summary><p class="hint">${r.allocation==='local-compression'?'压缩设备分配到本区产气点。':r.allocation==='local-decompression'?'解压设备分配到本区普通用气点。':r.allocation==='local-disposal'?'本区净过剩气体 / 液体就地处理。':'本区完整工艺配方。'} 配方栏列每次制作投入/产出，下方列当前每秒流量。概率产物使用期望值。</p><div class="zone-formula"><div><strong>每次投入</strong>${formula(def.ingredients)}</div><div><strong>每次产出</strong>${formula(def.results)}</div></div></details>`;}).join(''):'<p class="empty">本区没有符合条件的配方。</p>';
}
for(const id of Object.keys(zoneDefaults))$(id).addEventListener($(id).tagName==='SELECT'?'change':'input',()=>{if(validate())renderZones(state());});
$('zoneMap').addEventListener('click',e=>{const button=e.target.closest('[data-zone]');if(!button)return;chosenZone=button.dataset.zone;$('zoneRecipeSearch').value='';$('zoneRecipeFilter').value='active';if(validate())renderZones(state());});
$('zoneToRail').addEventListener('click',()=>{if(!validate())return;$('railSource').value='zone-'+$('zoneLayout').value;$('railStage').value=$('zoneStage').value;$('railPreset').value='remote';applyRailPreset('remote');renderRail(state());setTab('rail');});
$('zoneExport').addEventListener('click',()=>{if(!validate())return;const s=state(),m=zonesModel(s),z=m.zone,scaleObject=o=>Object.fromEntries(Object.entries(o).map(([k,v])=>[k,v*s.scale]));const data={scenario:m.plan.name,layout:m.layout,rate_each_pack_per_second:s.rate,unit_note:'Fluid actual units/s; item/box/barrel prototype units/s. Net interfaces after internal reuse.',zone:z.name,workshops:z.members.map(id=>workshopById[id]),net_per_second:scaleObject(z.net),internal_reuse_per_second:scaleObject(z.internal_reuse),disposal_per_second:scaleObject(z.disposal),recipes:z.recipes.map(r=>({...r,crafts_per_second:r.crafts_per_second*s.scale,machines:r.machines*s.scale,MW:r.MW*s.scale,definition:ZONING.definitions[r.recipe]}))};const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download=`nullius-${m.plan.name}-${m.layout}-${z.id}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);});
// Insert alongside logistics without changing the other report tabs.
const zoneTab=document.createElement('button');zoneTab.id='tab-zones';zoneTab.dataset.tab='zones';zoneTab.role='tab';zoneTab.setAttribute('aria-controls','zones');zoneTab.setAttribute('aria-selected','false');zoneTab.tabIndex=-1;zoneTab.textContent='分区施工清单';$('tab-rail').before(zoneTab);zoneTab.addEventListener('click',()=>setTab('zones'));
zoneTab.addEventListener('keydown',e=>{let tabs=[...document.querySelectorAll('[data-tab]')],i=tabs.indexOf(zoneTab);if(['ArrowLeft','ArrowRight','Home','End'].includes(e.key)){e.preventDefault();i=e.key==='Home'?0:e.key==='End'?tabs.length-1:(i+(e.key==='ArrowRight'?1:-1)+tabs.length)%tabs.length;setTab(tabs[i].dataset.tab);tabs[i].focus();}});
resetZones();
